//! C ABI for Dwell's network front-end (ADRs 0001, 0008).
//!
//! Phase 0 only proves the Rust ↔ C++ build and ABI plumbing. Sessions, streams, and datagrams
//! (`wtransport`) and the WebRTC fallback (`str0m`) arrive in Phase 1. The C header
//! `include/dwell_net.h` is generated by cbindgen (`gen-header.sh`) and checked in.

/// Version of this C ABI. Bumped on any incompatible change to the exported functions.
pub const DWELL_NET_ABI_VERSION: u32 = 1;

/// Returns the C ABI version implemented by this library (see `DWELL_NET_ABI_VERSION`).
#[unsafe(no_mangle)]
pub extern "C" fn dwell_net_abi_version() -> u32 {
    DWELL_NET_ABI_VERSION
}

/// Returns this crate's version as a NUL-terminated static string (e.g. "0.0.0").
#[unsafe(no_mangle)]
pub extern "C" fn dwell_net_crate_version() -> *const core::ffi::c_char {
    concat!(env!("CARGO_PKG_VERSION"), "\0").as_ptr().cast()
}

#[cfg(test)]
mod tests {
    use super::*;
    use core::ffi::CStr;

    #[test]
    fn abi_version_is_exported() {
        assert_eq!(dwell_net_abi_version(), DWELL_NET_ABI_VERSION);
    }

    #[test]
    fn crate_version_is_nul_terminated() {
        // SAFETY: the pointer refers to a static NUL-terminated string.
        let v = unsafe { CStr::from_ptr(dwell_net_crate_version()) };
        assert_eq!(v.to_str().unwrap(), env!("CARGO_PKG_VERSION"));
    }
}
