//! C ABI for Dwell's network front-end (ADRs 0001, 0008).
//!
//! The host (C++ server) starts a [`DwellNet`], drains events with [`dwell_net_poll`] once per
//! tick, and sends with [`dwell_net_send_reliable`] / [`dwell_net_send_datagram`]. All networking
//! runs on the crate's own tokio threads; nothing calls back into the host. The C header
//! `include/dwell_net.h` is generated by cbindgen (`gen-header.sh`) and checked in.

mod framing;
mod rtc;
mod server;

use std::cell::RefCell;
use std::ffi::{CStr, CString, c_char};
use std::net::IpAddr;

use server::{Command, Event, Limits, NetServer, StartOptions};

/// Version of this C ABI. Bumped on any incompatible change to the exported functions.
pub const DWELL_NET_ABI_VERSION: u32 = 3;

/// Opaque network front-end handle.
pub struct DwellNet {
    server: NetServer,
    ice_ufrag: CString,
    ice_pwd: CString,
    /// Payload of the last polled event; valid until the next poll.
    current: Vec<u8>,
}

#[repr(C)]
pub struct DwellNetConfig {
    /// WebTransport UDP port (0 = any free port).
    pub port: u16,
    /// WebRTC UDP port (0 = WebTransport port + 1).
    pub rtc_port: u16,
    /// NUL-terminated IP address clients use to reach the server (e.g. "127.0.0.1"); advertised
    /// in invite links and used as the WebRTC host candidate.
    pub advertised_ip: *const c_char,
    pub max_reliable_message_bytes: u32,
    pub max_datagram_bytes: u32,
}

#[repr(C)]
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum DwellNetEventKind {
    None = 0,
    Connected = 1,
    Disconnected = 2,
    Reliable = 3,
    Datagram = 4,
}

#[repr(C)]
pub struct DwellNetEvent {
    pub kind: DwellNetEventKind,
    pub session: u32,
    /// Connected: transport kind (protocol TransportKind; 1 = WebTransport, 2 = WebRTC).
    pub transport: u8,
    /// Reliable: channel id (0 = control, 1 = world).
    pub channel: u8,
    /// Connected: transport binding: SHA-256 of the server certificate (shared by WebTransport and
    /// WebRTC DTLS).
    pub binding: [u8; 32],
    /// Reliable/Datagram payload, valid until the next `dwell_net_poll` on this handle.
    pub data: *const u8,
    pub len: usize,
}

thread_local! {
    static LAST_ERROR: RefCell<CString> = RefCell::new(CString::default());
}

fn set_last_error(message: String) {
    let message = CString::new(message.replace('\0', " ")).unwrap_or_default();
    LAST_ERROR.with(|e| *e.borrow_mut() = message);
}

/// Returns the C ABI version implemented by this library (see `DWELL_NET_ABI_VERSION`).
#[unsafe(no_mangle)]
pub extern "C" fn dwell_net_abi_version() -> u32 {
    DWELL_NET_ABI_VERSION
}

/// Returns this crate's version as a NUL-terminated static string.
#[unsafe(no_mangle)]
pub extern "C" fn dwell_net_crate_version() -> *const c_char {
    concat!(env!("CARGO_PKG_VERSION"), "\0").as_ptr().cast()
}

/// Last error from `dwell_net_start` on this thread, as a NUL-terminated string (empty if none).
/// Valid until the next failing call on the same thread.
#[unsafe(no_mangle)]
pub extern "C" fn dwell_net_last_error() -> *const c_char {
    LAST_ERROR.with(|e| e.borrow().as_ptr())
}

/// Starts listening. Returns NULL on failure (see `dwell_net_last_error`).
///
/// # Safety
/// `config` must point to a valid `DwellNetConfig` whose `advertised_ip` is NULL or a valid
/// NUL-terminated string.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_start(config: *const DwellNetConfig) -> *mut DwellNet {
    // SAFETY: caller guarantees `config` is valid (or NULL, handled below).
    let Some(config) = (unsafe { config.as_ref() }) else {
        set_last_error("config is NULL".into());
        return std::ptr::null_mut();
    };
    let limits = Limits {
        max_reliable_message_bytes: config.max_reliable_message_bytes,
        max_datagram_bytes: config.max_datagram_bytes,
    };
    let advertised_ip = if config.advertised_ip.is_null() {
        "127.0.0.1".to_string()
    } else {
        // SAFETY: caller guarantees a valid NUL-terminated string.
        unsafe { CStr::from_ptr(config.advertised_ip) }
            .to_string_lossy()
            .into_owned()
    };
    let Ok(advertised_ip) = advertised_ip.parse::<IpAddr>() else {
        set_last_error(format!(
            "advertised_ip {advertised_ip:?} is not an IP address"
        ));
        return std::ptr::null_mut();
    };
    let options = StartOptions {
        port: config.port,
        rtc_port: config.rtc_port,
        advertised_ip,
        limits,
    };
    match NetServer::start(options) {
        Ok(server) => {
            let (ufrag, pwd) = server.ice_credentials();
            let ice_ufrag = CString::new(ufrag).unwrap_or_default();
            let ice_pwd = CString::new(pwd).unwrap_or_default();
            Box::into_raw(Box::new(DwellNet {
                server,
                ice_ufrag,
                ice_pwd,
                current: Vec::new(),
            }))
        }
        Err(e) => {
            set_last_error(e);
            std::ptr::null_mut()
        }
    }
}

/// Stops listening, closes all sessions, and frees the handle. NULL is ignored.
///
/// # Safety
/// `net` must be NULL or a handle from `dwell_net_start` not yet stopped.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_stop(net: *mut DwellNet) {
    if !net.is_null() {
        // SAFETY: `net` came from Box::into_raw in dwell_net_start and is freed only here.
        let net = unsafe { Box::from_raw(net) };
        net.server.shutdown();
    }
}

/// Writes the 32-byte SHA-256 of the server certificate (for `serverCertificateHashes`).
///
/// # Safety
/// `net` must be a live handle; `out` must point to 32 writable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_cert_hash(net: *const DwellNet, out: *mut u8) {
    // SAFETY: guaranteed by the caller.
    unsafe {
        let hash = (*net).server.cert_hash();
        std::ptr::copy_nonoverlapping(hash.as_ptr(), out, hash.len());
    }
}

/// The UDP port actually bound.
///
/// # Safety
/// `net` must be a live handle.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_port(net: *const DwellNet) -> u16 {
    // SAFETY: guaranteed by the caller.
    unsafe { (*net).server.port() }
}

/// The WebRTC UDP port actually bound.
///
/// # Safety
/// `net` must be a live handle.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_rtc_port(net: *const DwellNet) -> u16 {
    // SAFETY: guaranteed by the caller.
    unsafe { (*net).server.rtc_port() }
}

/// The server's WebRTC ICE username fragment (NUL-terminated; valid while the handle lives).
///
/// # Safety
/// `net` must be a live handle.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_ice_ufrag(net: *const DwellNet) -> *const c_char {
    // SAFETY: guaranteed by the caller.
    unsafe { (*net).ice_ufrag.as_ptr() }
}

/// The server's WebRTC ICE password (NUL-terminated; valid while the handle lives).
///
/// # Safety
/// `net` must be a live handle.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_ice_pwd(net: *const DwellNet) -> *const c_char {
    // SAFETY: guaranteed by the caller.
    unsafe { (*net).ice_pwd.as_ptr() }
}

/// Takes the next transport event. Returns false (and sets `kind = None`) when the queue is empty.
///
/// # Safety
/// `net` must be a live handle; `out` must point to a writable `DwellNetEvent`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_poll(net: *mut DwellNet, out: *mut DwellNetEvent) -> bool {
    // SAFETY: guaranteed by the caller.
    let (net, out) = unsafe { (&mut *net, &mut *out) };
    *out = DwellNetEvent {
        kind: DwellNetEventKind::None,
        session: 0,
        transport: 0,
        channel: 0,
        binding: [0; 32],
        data: std::ptr::null(),
        len: 0,
    };
    let Some(event) = net.server.poll() else {
        return false;
    };
    match event {
        Event::Connected {
            session,
            transport,
            binding,
        } => {
            out.kind = DwellNetEventKind::Connected;
            out.session = session;
            out.transport = transport;
            out.binding = binding;
        }
        Event::Disconnected { session } => {
            out.kind = DwellNetEventKind::Disconnected;
            out.session = session;
        }
        Event::Reliable {
            session,
            channel,
            data,
        } => {
            net.current = data;
            out.kind = DwellNetEventKind::Reliable;
            out.session = session;
            out.channel = channel;
        }
        Event::Datagram { session, data } => {
            net.current = data;
            out.kind = DwellNetEventKind::Datagram;
            out.session = session;
        }
    }
    if matches!(
        out.kind,
        DwellNetEventKind::Reliable | DwellNetEventKind::Datagram
    ) {
        out.data = net.current.as_ptr();
        out.len = net.current.len();
    }
    true
}

/// Queues a reliable message on `channel` (0 = control, 1 = world). False if the session is gone.
///
/// # Safety
/// `net` must be a live handle; `data` must point to `len` readable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_send_reliable(
    net: *const DwellNet,
    session: u32,
    channel: u8,
    data: *const u8,
    len: usize,
) -> bool {
    // SAFETY: guaranteed by the caller.
    let (net, data) = unsafe { (&*net, std::slice::from_raw_parts(data, len)) };
    net.server.send(
        session,
        Command::Reliable {
            channel,
            data: data.to_vec(),
        },
    )
}

/// Queues an unreliable datagram. False if the session is gone.
///
/// # Safety
/// `net` must be a live handle; `data` must point to `len` readable bytes.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_send_datagram(
    net: *const DwellNet,
    session: u32,
    data: *const u8,
    len: usize,
) -> bool {
    // SAFETY: guaranteed by the caller.
    let (net, data) = unsafe { (&*net, std::slice::from_raw_parts(data, len)) };
    net.server.send(session, Command::Datagram(data.to_vec()))
}

/// Closes a session after flushing queued reliable messages. A `Disconnected` event follows.
///
/// # Safety
/// `net` must be a live handle.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn dwell_net_close(net: *const DwellNet, session: u32) {
    // SAFETY: guaranteed by the caller.
    unsafe { (*net).server.send(session, Command::Close) };
}

#[cfg(test)]
mod tests {
    use super::*;
    use core::ffi::CStr;

    #[test]
    fn abi_version_is_exported() {
        assert_eq!(dwell_net_abi_version(), DWELL_NET_ABI_VERSION);
    }

    #[test]
    fn crate_version_is_nul_terminated() {
        // SAFETY: the pointer refers to a static NUL-terminated string.
        let v = unsafe { CStr::from_ptr(dwell_net_crate_version()) };
        assert_eq!(v.to_str().unwrap(), env!("CARGO_PKG_VERSION"));
    }
}
