// Generated by shared/protocol/gen.mjs from shared/protocol/constants.json. Do not edit.

export const PROTOCOL_VERSION = 2;
export const SIM_HZ = 60;
export const SNAPSHOT_HZ = 20;
export const MAX_DATAGRAM_BYTES = 1200;
export const MAX_RELIABLE_MESSAGE_BYTES = 1048576;
export const CHUNK_SIZE = 32;
export const AUTH_DOMAIN_TAG = 'dwell-auth-v1';
export const MAX_INPUTS_PER_DATAGRAM = 4;

export const Players = {
  maxHealth: 100,
  respawnSeconds: 5,
  reconcileSnapDistance: 1,
  interpDelayMs: 100,
  predictProxyRadius: 16,
} as const;

export const Limits = {
  displayNameMaxBytes: 64,
  clientVersionMaxBytes: 64,
  serverNameMaxBytes: 64,
  motdMaxBytes: 256,
  rejectMessageMaxBytes: 256,
} as const;

export const Channel = {
  control: 0,
  world: 1,
} as const;
export type Channel = (typeof Channel)[keyof typeof Channel];

export const MessageType = {
  PlayerInput: 1,
  DatagramPing: 2,
  DatagramPong: 130,
  StatusRequest: 64,
  StatusResponse: 65,
  ClientHello: 66,
  Challenge: 67,
  ClientAuth: 68,
  Welcome: 69,
  Reject: 70,
  Ping: 71,
  Pong: 72,
  PlayerEvent: 48,
  PhysicsSnapshot: 129,
} as const;
export type MessageType = (typeof MessageType)[keyof typeof MessageType];

export const RejectReason = {
  ProtocolVersion: 1,
  Banned: 2,
  Full: 3,
  NotAllowListed: 4,
  AuthFailed: 5,
  Malformed: 6,
  Replaced: 7,
} as const;
export type RejectReason = (typeof RejectReason)[keyof typeof RejectReason];

export const TransportKind = {
  WebTransport: 1,
  WebRtc: 2,
  Loopback: 3,
} as const;
export type TransportKind = (typeof TransportKind)[keyof typeof TransportKind];

export const PlayerState = {
  Idle: 0,
  Walking: 1,
  Running: 2,
  Crouching: 3,
  Sliding: 4,
  Jumping: 5,
  Falling: 6,
  Climbing: 7,
  Swimming: 8,
} as const;
export type PlayerState = (typeof PlayerState)[keyof typeof PlayerState];

export const GroundKind = {
  None: 0,
  Terrain: 1,
  Tier1Body: 2,
  Player: 3,
} as const;
export type GroundKind = (typeof GroundKind)[keyof typeof GroundKind];

export const PlayerEventKind = {
  Knockback: 1,
  Damage: 2,
  Death: 3,
  Respawn: 4,
} as const;
export type PlayerEventKind = (typeof PlayerEventKind)[keyof typeof PlayerEventKind];

export const DamageCause = {
  Fall: 1,
  Crush: 2,
  Explosion: 3,
} as const;
export type DamageCause = (typeof DamageCause)[keyof typeof DamageCause];

export const InputButtons = {
  jump: 1,
  run: 2,
  crouch: 4,
} as const;

export const PlayerFlags = {
  grounded: 1,
  crouched: 2,
  climbing: 4,
  swimming: 8,
  dead: 16,
} as const;

export const ControllerFlags = {
  grounded: 1,
  jumping: 2,
  crouching: 4,
  climbing: 8,
  hasReleased: 16,
  swimming: 32,
} as const;
