// Generated by shared/protocol/gen.mjs from shared/protocol/constants.json. Do not edit.

export const PROTOCOL_VERSION = 1;
export const SIM_HZ = 60;
export const SNAPSHOT_HZ = 20;
export const MAX_DATAGRAM_BYTES = 1200;
export const MAX_RELIABLE_MESSAGE_BYTES = 1048576;
export const CHUNK_SIZE = 32;
export const AUTH_DOMAIN_TAG = 'dwell-auth-v1';

export const Limits = {
  displayNameMaxBytes: 64,
  clientVersionMaxBytes: 64,
  serverNameMaxBytes: 64,
  motdMaxBytes: 256,
  rejectMessageMaxBytes: 256,
} as const;

export const Channel = {
  control: 0,
  world: 1,
} as const;
export type Channel = (typeof Channel)[keyof typeof Channel];

export const MessageType = {
  DatagramPing: 2,
  DatagramPong: 130,
  StatusRequest: 64,
  StatusResponse: 65,
  ClientHello: 66,
  Challenge: 67,
  ClientAuth: 68,
  Welcome: 69,
  Reject: 70,
  Ping: 71,
  Pong: 72,
} as const;
export type MessageType = (typeof MessageType)[keyof typeof MessageType];

export const RejectReason = {
  ProtocolVersion: 1,
  Banned: 2,
  Full: 3,
  NotAllowListed: 4,
  AuthFailed: 5,
  Malformed: 6,
  Replaced: 7,
} as const;
export type RejectReason = (typeof RejectReason)[keyof typeof RejectReason];

export const TransportKind = {
  WebTransport: 1,
  WebRtc: 2,
  Loopback: 3,
} as const;
export type TransportKind = (typeof TransportKind)[keyof typeof TransportKind];
