// Generated by shared/blocks/gen.mjs from shared/blocks/*.json. Do not edit.
import type { TileName } from '../render/textures';

export type MaterialLook = 'cube' | 'slab' | 'ladder' | 'water';

/** Texture tiles (render/textures.ts) per face group; untextured materials use `color`. */
export interface MaterialTextures {
  top: TileName;
  side: TileName;
  bottom: TileName;
}

export interface BlockProperty {
  name: string;
  values: readonly string[];
}

/** A block: a namespaced id, its typed properties and the run of runtime state ids it owns. */
export interface BlockDef {
  id: string;
  first: number;
  count: number;
  properties: readonly BlockProperty[];
}

/** One block state with how it is drawn (the physics side lives in the C++ core). */
export interface StateDef {
  /** Runtime state id. */
  id: number;
  /** Canonical string: `ns:name[k=v,…]`, every property, keys alphabetical. */
  state: string;
  block: number;
  values: Readonly<Record<string, string>>;
  look: MaterialLook;
  color: number;
  opacity: number;
  textures?: MaterialTextures;
  /** Ladders: the face whose side the plate faces (0 +X, 1 −X, 4 +Z, 5 −Z). */
  ladderFace?: number;
  /** In the infinite creative palette (§6.5; C++ `Placeable`). */
  placeable: boolean;
}

/** FNV-1a 64 over the canonical state strings (each followed by "\n") in id order. */
export const REGISTRY_HASH = 0x160e5ffd3cc97380n;

export const BLOCK_DEFS: readonly BlockDef[] = [
  { id: 'dwell:air', first: 0, count: 1, properties: [] },
  { id: 'dwell:bedrock', first: 1, count: 1, properties: [] },
  { id: 'dwell:stone', first: 2, count: 1, properties: [] },
  { id: 'dwell:dirt', first: 3, count: 1, properties: [] },
  { id: 'dwell:grass', first: 4, count: 1, properties: [] },
  { id: 'dwell:stone_slab', first: 5, count: 1, properties: [] },
  { id: 'dwell:ladder', first: 6, count: 8, properties: [{ name: 'facing', values: ['north', 'east', 'south', 'west'] }, { name: 'flooded', values: ['false', 'true'] }] },
  { id: 'dwell:water', first: 14, count: 1, properties: [] },
  { id: 'dwell:launch_pad', first: 15, count: 1, properties: [] },
  { id: 'dwell:sand', first: 16, count: 1, properties: [] },
  { id: 'dwell:sandstone', first: 17, count: 1, properties: [] },
  { id: 'dwell:gravel', first: 18, count: 1, properties: [] },
  { id: 'dwell:snow', first: 19, count: 1, properties: [] },
  { id: 'dwell:log', first: 20, count: 1, properties: [] },
  { id: 'dwell:leaves', first: 21, count: 1, properties: [] },
  { id: 'dwell:coal_ore', first: 22, count: 1, properties: [] },
  { id: 'dwell:iron_ore', first: 23, count: 1, properties: [] },
  { id: 'dwell:gold_ore', first: 24, count: 1, properties: [] },
];

export const STATE_DEFS: readonly StateDef[] = [
  { id: 0, state: 'dwell:air', block: 0, values: {  }, look: 'cube', color: 0x000000, opacity: 0, placeable: false },
  { id: 1, state: 'dwell:bedrock', block: 1, values: {  }, look: 'cube', color: 0x4e4858, opacity: 1, textures: { top: 'bedrock', side: 'bedrock', bottom: 'bedrock' }, placeable: false },
  { id: 2, state: 'dwell:stone', block: 2, values: {  }, look: 'cube', color: 0xbbafa6, opacity: 1, textures: { top: 'stone', side: 'stone', bottom: 'stone' }, placeable: true },
  { id: 3, state: 'dwell:dirt', block: 3, values: {  }, look: 'cube', color: 0x8a5a3a, opacity: 1, textures: { top: 'dirt', side: 'dirt', bottom: 'dirt' }, placeable: true },
  { id: 4, state: 'dwell:grass', block: 4, values: {  }, look: 'cube', color: 0x8dbf3f, opacity: 1, textures: { top: 'grass', side: 'grassSide', bottom: 'dirt' }, placeable: true },
  { id: 5, state: 'dwell:stone_slab', block: 5, values: {  }, look: 'slab', color: 0xc8bdb4, opacity: 1, textures: { top: 'stone', side: 'stone', bottom: 'stone' }, placeable: true },
  { id: 6, state: 'dwell:ladder[facing=north,flooded=false]', block: 6, values: { facing: 'north', flooded: 'false' }, look: 'ladder', color: 0xa0703a, opacity: 1, textures: { top: 'ladder', side: 'ladder', bottom: 'ladder' }, ladderFace: 5, placeable: true },
  { id: 7, state: 'dwell:ladder[facing=north,flooded=true]', block: 6, values: { facing: 'north', flooded: 'true' }, look: 'ladder', color: 0xa0703a, opacity: 1, textures: { top: 'ladder', side: 'ladder', bottom: 'ladder' }, ladderFace: 5, placeable: false },
  { id: 8, state: 'dwell:ladder[facing=east,flooded=false]', block: 6, values: { facing: 'east', flooded: 'false' }, look: 'ladder', color: 0xa0703a, opacity: 1, textures: { top: 'ladder', side: 'ladder', bottom: 'ladder' }, ladderFace: 0, placeable: true },
  { id: 9, state: 'dwell:ladder[facing=east,flooded=true]', block: 6, values: { facing: 'east', flooded: 'true' }, look: 'ladder', color: 0xa0703a, opacity: 1, textures: { top: 'ladder', side: 'ladder', bottom: 'ladder' }, ladderFace: 0, placeable: false },
  { id: 10, state: 'dwell:ladder[facing=south,flooded=false]', block: 6, values: { facing: 'south', flooded: 'false' }, look: 'ladder', color: 0xa0703a, opacity: 1, textures: { top: 'ladder', side: 'ladder', bottom: 'ladder' }, ladderFace: 4, placeable: true },
  { id: 11, state: 'dwell:ladder[facing=south,flooded=true]', block: 6, values: { facing: 'south', flooded: 'true' }, look: 'ladder', color: 0xa0703a, opacity: 1, textures: { top: 'ladder', side: 'ladder', bottom: 'ladder' }, ladderFace: 4, placeable: false },
  { id: 12, state: 'dwell:ladder[facing=west,flooded=false]', block: 6, values: { facing: 'west', flooded: 'false' }, look: 'ladder', color: 0xa0703a, opacity: 1, textures: { top: 'ladder', side: 'ladder', bottom: 'ladder' }, ladderFace: 1, placeable: true },
  { id: 13, state: 'dwell:ladder[facing=west,flooded=true]', block: 6, values: { facing: 'west', flooded: 'true' }, look: 'ladder', color: 0xa0703a, opacity: 1, textures: { top: 'ladder', side: 'ladder', bottom: 'ladder' }, ladderFace: 1, placeable: false },
  { id: 14, state: 'dwell:water', block: 7, values: {  }, look: 'water', color: 0x3fb2d6, opacity: 0.55, textures: { top: 'water', side: 'water', bottom: 'water' }, placeable: false },
  { id: 15, state: 'dwell:launch_pad', block: 8, values: {  }, look: 'cube', color: 0xe8792a, opacity: 1, textures: { top: 'launchPad', side: 'stone', bottom: 'stone' }, placeable: false },
  { id: 16, state: 'dwell:sand', block: 9, values: {  }, look: 'cube', color: 0xeed9a4, opacity: 1, textures: { top: 'sand', side: 'sand', bottom: 'sand' }, placeable: true },
  { id: 17, state: 'dwell:sandstone', block: 10, values: {  }, look: 'cube', color: 0xe0be86, opacity: 1, textures: { top: 'sandstone', side: 'sandstone', bottom: 'sandstone' }, placeable: true },
  { id: 18, state: 'dwell:gravel', block: 11, values: {  }, look: 'cube', color: 0xa3968e, opacity: 1, textures: { top: 'gravel', side: 'gravel', bottom: 'gravel' }, placeable: true },
  { id: 19, state: 'dwell:snow', block: 12, values: {  }, look: 'cube', color: 0xfbf8f2, opacity: 1, textures: { top: 'snow', side: 'snow', bottom: 'snow' }, placeable: true },
  { id: 20, state: 'dwell:log', block: 13, values: {  }, look: 'cube', color: 0x7a5236, opacity: 1, textures: { top: 'logTop', side: 'logSide', bottom: 'logTop' }, placeable: true },
  { id: 21, state: 'dwell:leaves', block: 14, values: {  }, look: 'cube', color: 0x6fa83a, opacity: 1, textures: { top: 'leaves', side: 'leaves', bottom: 'leaves' }, placeable: true },
  { id: 22, state: 'dwell:coal_ore', block: 15, values: {  }, look: 'cube', color: 0xbbafa6, opacity: 1, textures: { top: 'coalOre', side: 'coalOre', bottom: 'coalOre' }, placeable: true },
  { id: 23, state: 'dwell:iron_ore', block: 16, values: {  }, look: 'cube', color: 0xbbafa6, opacity: 1, textures: { top: 'ironOre', side: 'ironOre', bottom: 'ironOre' }, placeable: true },
  { id: 24, state: 'dwell:gold_ore', block: 17, values: {  }, look: 'cube', color: 0xbbafa6, opacity: 1, textures: { top: 'goldOre', side: 'goldOre', bottom: 'goldOre' }, placeable: true },
];
