#!/usr/bin/env node
// Generates protocol constants for C++ and TypeScript from constants.json.
// Outputs are checked in; CI regenerates and fails on any diff.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const c = JSON.parse(readFileSync(join(here, 'constants.json'), 'utf8'));
const header = 'Generated by shared/protocol/gen.mjs from shared/protocol/constants.json. Do not edit.';

const enumEntries = (obj) => Object.entries(obj);

// ---- C++ -----------------------------------------------------------------------------------------
const cpp = [];
cpp.push(`// ${header}`);
cpp.push('#pragma once');
cpp.push('');
cpp.push('#include <cstddef>');
cpp.push('#include <cstdint>');
cpp.push('#include <string_view>');
cpp.push('');
cpp.push('namespace dwell::protocol {');
cpp.push('');
cpp.push(`inline constexpr std::uint16_t kProtocolVersion = ${c.protocolVersion};`);
cpp.push(`inline constexpr int kSimHz = ${c.simHz};`);
cpp.push(`inline constexpr int kSnapshotHz = ${c.snapshotHz};`);
cpp.push(`inline constexpr std::size_t kMaxDatagramBytes = ${c.maxDatagramBytes};`);
cpp.push(`inline constexpr std::size_t kMaxReliableMessageBytes = ${c.maxReliableMessageBytes};`);
cpp.push(`inline constexpr int kChunkSize = ${c.chunkSize};`);
cpp.push(`inline constexpr std::string_view kAuthDomainTag = "${c.authDomainTag}";`);
cpp.push('');
for (const [k, v] of enumEntries(c.limits)) {
  cpp.push(`inline constexpr std::size_t k${k[0].toUpperCase()}${k.slice(1)} = ${v};`);
}
const cppEnum = (name, type, obj) => {
  cpp.push('');
  cpp.push(`enum class ${name} : ${type} {`);
  for (const [k, v] of enumEntries(obj)) cpp.push(`  k${k[0].toUpperCase()}${k.slice(1)} = ${v},`);
  cpp.push('};');
};
cppEnum('Channel', 'std::uint8_t', c.channels);
cppEnum('MessageType', 'std::uint8_t', c.messageTypes);
cppEnum('RejectReason', 'std::uint8_t', c.rejectReasons);
cpp.push(`inline constexpr std::uint8_t kMaxRejectReason = ${Math.max(...Object.values(c.rejectReasons))};`);
cppEnum('TransportKind', 'std::uint8_t', c.transportKinds);
cpp.push('');
cpp.push('}  // namespace dwell::protocol');
cpp.push('');
writeFileSync(join(root, 'server/core/include/dwell/protocol/constants.gen.h'), cpp.join('\n'));

// ---- TypeScript ----------------------------------------------------------------------------------
const ts = [];
ts.push(`// ${header}`);
ts.push('');
ts.push(`export const PROTOCOL_VERSION = ${c.protocolVersion};`);
ts.push(`export const SIM_HZ = ${c.simHz};`);
ts.push(`export const SNAPSHOT_HZ = ${c.snapshotHz};`);
ts.push(`export const MAX_DATAGRAM_BYTES = ${c.maxDatagramBytes};`);
ts.push(`export const MAX_RELIABLE_MESSAGE_BYTES = ${c.maxReliableMessageBytes};`);
ts.push(`export const CHUNK_SIZE = ${c.chunkSize};`);
ts.push(`export const AUTH_DOMAIN_TAG = '${c.authDomainTag}';`);
ts.push('');
ts.push('export const Limits = {');
for (const [k, v] of enumEntries(c.limits)) ts.push(`  ${k}: ${v},`);
ts.push('} as const;');
const tsEnum = (name, obj) => {
  ts.push('');
  ts.push(`export const ${name} = {`);
  for (const [k, v] of enumEntries(obj)) ts.push(`  ${k}: ${v},`);
  ts.push('} as const;');
  ts.push(`export type ${name} = (typeof ${name})[keyof typeof ${name}];`);
};
tsEnum('Channel', c.channels);
tsEnum('MessageType', c.messageTypes);
tsEnum('RejectReason', c.rejectReasons);
tsEnum('TransportKind', c.transportKinds);
ts.push('');
writeFileSync(join(root, 'client/src/protocol/constants.gen.ts'), ts.join('\n'));

