#!/usr/bin/env python3
"""Reference encoder for protocol golden vectors (independent of the C++ and TS codecs).

Writes shared/protocol/vectors.txt. Each line is `<name> <hex>`; names starting with `!` are
malformed inputs that every decoder must reject. The field values used here are mirrored in the
C++ (server/tests/protocol_test.cpp) and TS (client/src/protocol/messages.test.ts) tests.
"""
import json
import struct
from pathlib import Path

here = Path(__file__).parent
c = json.loads((here / "constants.json").read_text())
T = c["messageTypes"]


def s(text: str) -> bytes:
    b = text.encode("utf-8")
    return struct.pack("<H", len(b)) + b


PK = bytes(range(32))
NONCE = bytes(range(0xA0, 0xC0))
SIG = bytes((i * 3) & 0xFF for i in range(64))
BINDING = bytes(range(0x10, 0x30))

vectors = {
    "datagram_ping": struct.pack("<BId", T["DatagramPing"], 0x01020304, 1234.5),
    "datagram_pong": struct.pack("<BIdI", T["DatagramPong"], 7, 0.25, 600),
    "status_request": struct.pack("<B", T["StatusRequest"]),
    "status_response": struct.pack("<BH", T["StatusResponse"], 1)
    + s("Dwell Test")
    + s("héllo ✓")
    + struct.pack("<HHB", 3, 8, 1),
    "client_hello": struct.pack("<BH", T["ClientHello"], 1) + s("0.1.0") + PK + s("Zack"),
    "challenge": struct.pack("<B", T["Challenge"]) + NONCE,
    "client_auth": struct.pack("<B", T["ClientAuth"]) + SIG,
    "welcome": struct.pack("<BHQII", T["Welcome"], 42, 0x0123456789ABCDEF, 7, 123456),
    "reject": struct.pack("<BB", T["Reject"], c["rejectReasons"]["ProtocolVersion"])
    + s("Server runs protocol 2"),
    "ping": struct.pack("<BId", T["Ping"], 9, 1000.0),
    "pong": struct.pack("<BIdId", T["Pong"], 9, 1000.0, 60, 5000.125),
    "auth_transcript": c["authDomainTag"].encode() + NONCE + BINDING + PK,
}

malformed = {
    "!empty": b"",
    "!unknown_type": bytes([0xEE]),
    "!truncated_ping": vectors["ping"][:-1],
    "!trailing_byte": vectors["welcome"] + b"\x00",
    "!bad_utf8": struct.pack("<BH", T["ClientHello"], 1)
    + struct.pack("<H", 2) + b"\xC3\x28" + PK + s("Zack"),
    "!name_too_long": struct.pack("<BH", T["ClientHello"], 1)
    + s("0.1.0") + PK + s("x" * (c["limits"]["displayNameMaxBytes"] + 1)),
    "!bad_reject_reason": struct.pack("<BB", T["Reject"], 0) + s("x"),
}

lines = ["# Generated by shared/protocol/make_vectors.py. Do not edit."]
lines += [f"{k} {v.hex()}" for k, v in {**vectors, **malformed}.items()]
(here / "vectors.txt").write_text("\n".join(lines) + "\n")
