// Generated by shared/blocks/gen.mjs from shared/blocks/*.json. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

#include "dwell/core/block_types.h"

namespace dwell::core {

inline constexpr std::size_t kBlockCount = 18;
inline constexpr std::size_t kPropertyCount = 2;
// FNV-1a 64 over the canonical state strings (each followed by '\n') in runtime id order.
inline constexpr std::uint64_t kRegistryHash = 0x160e5ffd3cc97380ull;

// Runtime state ids, by name (non-default property values are appended to the name).
namespace Materials {
inline constexpr MaterialId kAir = 0;
inline constexpr MaterialId kBedrock = 1;
inline constexpr MaterialId kStone = 2;
inline constexpr MaterialId kDirt = 3;
inline constexpr MaterialId kGrass = 4;
inline constexpr MaterialId kStoneSlab = 5;
inline constexpr MaterialId kLadder = 6;
inline constexpr MaterialId kLadderFloodedTrue = 7;
inline constexpr MaterialId kLadderFacingEast = 8;
inline constexpr MaterialId kLadderFacingEastFloodedTrue = 9;
inline constexpr MaterialId kLadderFacingSouth = 10;
inline constexpr MaterialId kLadderFacingSouthFloodedTrue = 11;
inline constexpr MaterialId kLadderFacingWest = 12;
inline constexpr MaterialId kLadderFacingWestFloodedTrue = 13;
inline constexpr MaterialId kWater = 14;
inline constexpr MaterialId kLaunchPad = 15;
inline constexpr MaterialId kSand = 16;
inline constexpr MaterialId kSandstone = 17;
inline constexpr MaterialId kGravel = 18;
inline constexpr MaterialId kSnow = 19;
inline constexpr MaterialId kLog = 20;
inline constexpr MaterialId kLeaves = 21;
inline constexpr MaterialId kCoalOre = 22;
inline constexpr MaterialId kIronOre = 23;
inline constexpr MaterialId kGoldOre = 24;
inline constexpr MaterialId kCount = 25;
}  // namespace Materials

inline constexpr std::array<std::string_view, 6> kPropertyValues{{
    "north",
    "east",
    "south",
    "west",
    "false",
    "true",
}};

inline constexpr std::array<PropertyDef, 2> kProperties{{
    {"facing", 0, 4},
    {"flooded", 4, 2},
}};

inline constexpr std::array<BlockDef, kBlockCount> kBlocks{{
    {"dwell:air", 0, 1, 0, 0},
    {"dwell:bedrock", 1, 1, 0, 0},
    {"dwell:stone", 2, 1, 0, 0},
    {"dwell:dirt", 3, 1, 0, 0},
    {"dwell:grass", 4, 1, 0, 0},
    {"dwell:stone_slab", 5, 1, 0, 0},
    {"dwell:ladder", 6, 8, 0, 2},
    {"dwell:water", 14, 1, 2, 0},
    {"dwell:launch_pad", 15, 1, 2, 0},
    {"dwell:sand", 16, 1, 2, 0},
    {"dwell:sandstone", 17, 1, 2, 0},
    {"dwell:gravel", 18, 1, 2, 0},
    {"dwell:snow", 19, 1, 2, 0},
    {"dwell:log", 20, 1, 2, 0},
    {"dwell:leaves", 21, 1, 2, 0},
    {"dwell:coal_ore", 22, 1, 2, 0},
    {"dwell:iron_ore", 23, 1, 2, 0},
    {"dwell:gold_ore", 24, 1, 2, 0},
}};

inline constexpr std::array<MaterialInfo, Materials::kCount> kMaterials{{
    {.name = "dwell:air", .density_kg_m3 = 0.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = false, .block = 0},  // 0
    {.name = "dwell:bedrock", .density_kg_m3 = 3000.0f, .solid = true, .indestructible = true, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = false, .block = 1},  // 1
    {.name = "dwell:stone", .density_kg_m3 = 2400.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 2},  // 2
    {.name = "dwell:dirt", .density_kg_m3 = 1500.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 3},  // 3
    {.name = "dwell:grass", .density_kg_m3 = 1400.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 4},  // 4
    {.name = "dwell:stone_slab", .density_kg_m3 = 2400.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kSlabBottom, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 5},  // 5
    {.name = "dwell:ladder[facing=north,flooded=false]", .density_kg_m3 = 600.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = true, .facing = Facing::kNorth, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 6},  // 6
    {.name = "dwell:ladder[facing=north,flooded=true]", .density_kg_m3 = 600.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = true, .facing = Facing::kNorth, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = false, .block = 6},  // 7
    {.name = "dwell:ladder[facing=east,flooded=false]", .density_kg_m3 = 600.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = true, .facing = Facing::kEast, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 6},  // 8
    {.name = "dwell:ladder[facing=east,flooded=true]", .density_kg_m3 = 600.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = true, .facing = Facing::kEast, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = false, .block = 6},  // 9
    {.name = "dwell:ladder[facing=south,flooded=false]", .density_kg_m3 = 600.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = true, .facing = Facing::kSouth, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 6},  // 10
    {.name = "dwell:ladder[facing=south,flooded=true]", .density_kg_m3 = 600.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = true, .facing = Facing::kSouth, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = false, .block = 6},  // 11
    {.name = "dwell:ladder[facing=west,flooded=false]", .density_kg_m3 = 600.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = true, .facing = Facing::kWest, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 6},  // 12
    {.name = "dwell:ladder[facing=west,flooded=true]", .density_kg_m3 = 600.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = true, .facing = Facing::kWest, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = false, .block = 6},  // 13
    {.name = "dwell:water", .density_kg_m3 = 1000.0f, .solid = false, .indestructible = false, .shape = VoxelShape::kEmpty, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = true, .launch_speed = 0.0f, .placeable = false, .block = 7},  // 14
    {.name = "dwell:launch_pad", .density_kg_m3 = 2400.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 14.0f, .placeable = false, .block = 8},  // 15
    {.name = "dwell:sand", .density_kg_m3 = 1600.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 9},  // 16
    {.name = "dwell:sandstone", .density_kg_m3 = 2200.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 10},  // 17
    {.name = "dwell:gravel", .density_kg_m3 = 1800.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 11},  // 18
    {.name = "dwell:snow", .density_kg_m3 = 500.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 12},  // 19
    {.name = "dwell:log", .density_kg_m3 = 700.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 13},  // 20
    {.name = "dwell:leaves", .density_kg_m3 = 200.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 14},  // 21
    {.name = "dwell:coal_ore", .density_kg_m3 = 2400.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 15},  // 22
    {.name = "dwell:iron_ore", .density_kg_m3 = 3200.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 16},  // 23
    {.name = "dwell:gold_ore", .density_kg_m3 = 3600.0f, .solid = true, .indestructible = false, .shape = VoxelShape::kFull, .climbable = false, .facing = Facing::kNone, .climb_speed_scale = 1.0f, .liquid = false, .launch_speed = 0.0f, .placeable = true, .block = 17},  // 24
}};

}  // namespace dwell::core
