// `versions.json`, the site's manifest of published builds (RELEASES.md §4): generated by
// scripts/site.ts from each release's `build.json`, read by the launcher.
import { isStable, parseVersion } from '../../src/version/semver';

export interface BuildEntry {
  version: string;
  channel: 'stable' | 'dev';
  date: string;
  commit: string;
  protocolVersion: number;
  /** The launcher this build needs (RELEASES.md §5); builds ask for newer ones when it changes. */
  minLauncher: number;
}

export interface Manifest {
  schema: 1;
  generated: string;
  /** Newest first. */
  versions: BuildEntry[];
  latestStable: string | null;
  latestDev: string | null;
}

/** The launcher's own version: the newest `minLauncher` it serves. */
export const LAUNCHER_VERSION = 1;

export function isBuildEntry(v: unknown): v is BuildEntry {
  if (typeof v !== 'object' || v === null) return false;
  const e = v as Record<string, unknown>;
  const parsed = typeof e.version === 'string' ? parseVersion(e.version) : null;
  return (
    parsed !== null &&
    e.channel === (isStable(parsed) ? 'stable' : 'dev') &&
    typeof e.date === 'string' &&
    typeof e.commit === 'string' &&
    Number.isInteger(e.protocolVersion) &&
    Number.isInteger(e.minLauncher)
  );
}

/** The manifest in parsed JSON, or null if it is not one (entries that don't parse are dropped). */
export function parseManifest(json: unknown): Manifest | null {
  if (typeof json !== 'object' || json === null) return null;
  const m = json as Record<string, unknown>;
  if (m.schema !== 1 || !Array.isArray(m.versions)) return null;
  const versions = m.versions.filter(isBuildEntry);
  const known = (v: unknown): string | null =>
    typeof v === 'string' && versions.some((e) => e.version === v) ? v : null;
  return {
    schema: 1,
    generated: typeof m.generated === 'string' ? m.generated : '',
    versions,
    latestStable: known(m.latestStable),
    latestDev: known(m.latestDev),
  };
}
