#ifndef DWELL_NET_H
#define DWELL_NET_H

/* Generated by cbindgen from server/net/wt/src/lib.rs. Do not edit; run gen-header.sh. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Version of this C ABI. Bumped on any incompatible change to the exported functions.
 */
#define DWELL_NET_ABI_VERSION 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns the C ABI version implemented by this library (see `DWELL_NET_ABI_VERSION`).
 */
uint32_t dwell_net_abi_version(void);

/**
 * Returns this crate's version as a NUL-terminated static string (e.g. "0.0.0").
 */
const char *dwell_net_crate_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* DWELL_NET_H */
