// Generated by shared/protocol/gen.mjs from shared/protocol/constants.json. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <string_view>

namespace dwell::protocol {

inline constexpr std::uint16_t kProtocolVersion = 1;
inline constexpr int kSimHz = 60;
inline constexpr int kSnapshotHz = 20;
inline constexpr std::size_t kMaxDatagramBytes = 1200;
inline constexpr std::size_t kMaxReliableMessageBytes = 1048576;
inline constexpr int kChunkSize = 32;
inline constexpr std::string_view kAuthDomainTag = "dwell-auth-v1";

inline constexpr std::size_t kDisplayNameMaxBytes = 64;
inline constexpr std::size_t kClientVersionMaxBytes = 64;
inline constexpr std::size_t kServerNameMaxBytes = 64;
inline constexpr std::size_t kMotdMaxBytes = 256;
inline constexpr std::size_t kRejectMessageMaxBytes = 256;

enum class Channel : std::uint8_t {
  kControl = 0,
  kWorld = 1,
};

enum class MessageType : std::uint8_t {
  kDatagramPing = 2,
  kDatagramPong = 130,
  kStatusRequest = 64,
  kStatusResponse = 65,
  kClientHello = 66,
  kChallenge = 67,
  kClientAuth = 68,
  kWelcome = 69,
  kReject = 70,
  kPing = 71,
  kPong = 72,
};

enum class RejectReason : std::uint8_t {
  kProtocolVersion = 1,
  kBanned = 2,
  kFull = 3,
  kNotAllowListed = 4,
  kAuthFailed = 5,
  kMalformed = 6,
};

enum class TransportKind : std::uint8_t {
  kWebTransport = 1,
  kWebRtc = 2,
  kLoopback = 3,
};

}  // namespace dwell::protocol
