#!/usr/bin/env node
// Generates the block registries for C++ and TypeScript from shared/blocks/*.json
// (docs/BLOCK_REGISTRY.md). Outputs are checked in; CI regenerates and fails on any diff.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const header = 'Generated by shared/blocks/gen.mjs from shared/blocks/*.json. Do not edit.';

// ---- Load and expand ---------------------------------------------------------------------------
const files = readdirSync(here)
  .filter((f) => f.endsWith('.json'))
  .sort();
const namespaces = files
  .map((f) => JSON.parse(readFileSync(join(here, f), 'utf8')))
  .sort((a, b) => (a.namespace < b.namespace ? -1 : a.namespace > b.namespace ? 1 : 0));

const NAME = /^[a-z0-9_]+$/;
const SHAPES = { empty: 'kEmpty', full: 'kFull', slab_bottom: 'kSlabBottom' };
const FACINGS = ['north', 'east', 'south', 'west'];
// The face (mesher axis·2 + sign) a ladder's plate sits against, per facing (0 +X, 1 −X, 4 +Z, 5 −Z).
const LADDER_FACE = { east: 0, west: 1, south: 4, north: 5 };
const LOOKS = ['cube', 'slab', 'ladder', 'water'];

const pascal = (s) => s.replace(/(^|_)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const fail = (m) => {
  throw new Error(`shared/blocks: ${m}`);
};

const blocks = []; // { id, def, props: [{name, values}], first, count }
const states = []; // { id, block, string, values: {prop: value}, ... }
for (const ns of namespaces) {
  if (!NAME.test(ns.namespace)) fail(`bad namespace ${ns.namespace}`);
  for (const def of ns.blocks) {
    if (!NAME.test(def.name)) fail(`bad block name ${def.name}`);
    const id = `${ns.namespace}:${def.name}`;
    if (blocks.some((b) => b.id === id)) fail(`duplicate block ${id}`);
    const props = Object.keys(def.properties ?? {})
      .sort()
      .map((name) => {
        if (!NAME.test(name)) fail(`${id}: bad property name ${name}`);
        const values = def.properties[name];
        if (!values.length || new Set(values).size !== values.length) fail(`${id}.${name}: values`);
        for (const v of values) if (!NAME.test(v)) fail(`${id}.${name}: bad value ${v}`);
        return { name, values };
      });
    if (!(def.shape in SHAPES)) fail(`${id}: shape ${def.shape}`);
    const look = def.look ?? 'cube';
    if (!LOOKS.includes(look)) fail(`${id}: look ${look}`);
    if (def.facingProperty) {
      const p = props.find((q) => q.name === def.facingProperty);
      if (!p || p.values.some((v) => !FACINGS.includes(v))) fail(`${id}: facingProperty`);
    }
    const count = props.reduce((n, p) => n * p.values.length, 1);
    const block = { id, def, props, first: states.length, count, look };
    blocks.push(block);
    // Mixed radix: the last (alphabetically) property varies fastest.
    for (let i = 0; i < count; ++i) {
      const values = {};
      let rest = i;
      for (let k = props.length - 1; k >= 0; --k) {
        const p = props[k];
        values[p.name] = p.values[rest % p.values.length];
        rest = Math.floor(rest / p.values.length);
      }
      const string = props.length
        ? `${id}[${props.map((p) => `${p.name}=${values[p.name]}`).join(',')}]`
        : id;
      states.push({ id: states.length, block, string, values });
    }
  }
}
if (states[0]?.string !== 'dwell:air') fail('dwell:air must be state 0');
if (states.length > 0xffff) fail('too many states');

// Palette (creative inventory) membership: a block's `palette` lists partial property assignments;
// `placeable` alone means the default state.
const defaultOf = (block) => Object.fromEntries(block.props.map((p) => [p.name, p.values[0]]));
for (const block of blocks) {
  const { def } = block;
  const entries = def.palette ?? (def.placeable ? [{}] : []);
  for (const entry of entries) {
    const want = { ...defaultOf(block), ...entry };
    const s = states.find(
      (st) => st.block === block && block.props.every((p) => st.values[p.name] === want[p.name]),
    );
    if (!s) fail(`${block.id}: palette entry ${JSON.stringify(entry)} matches no state`);
    s.placeable = true;
  }
}

// ---- Registry hash: FNV-1a 64 over each canonical string followed by "\n", in id order ------------
function registryHash() {
  let h = 0xcbf29ce484222325n;
  for (const s of states) {
    for (const byte of Buffer.from(`${s.string}\n`, 'utf8')) {
      h ^= BigInt(byte);
      h = (h * 0x100000001b3n) & 0xffffffffffffffffn;
    }
  }
  return h;
}
const hash = registryHash();
const hashHex = hash.toString(16).padStart(16, '0');

// Constant names: PascalCase block name, plus Property+Value for every non-default value.
const constName = (s) => {
  let n = `k${pascal(s.block.def.name)}`;
  for (const p of s.block.props) {
    if (s.values[p.name] !== p.values[0]) n += pascal(p.name) + pascal(s.values[p.name]);
  }
  return n;
};
const seen = new Set();
for (const s of states) {
  s.constName = constName(s);
  if (seen.has(s.constName)) fail(`constant name clash ${s.constName}`);
  seen.add(s.constName);
}

const colorNum = (c) => `0x${c.replace('#', '').toLowerCase()}`;
const num = (v) => (Number.isInteger(v) ? `${v}.0f` : `${v}f`);

// ---- C++ ---------------------------------------------------------------------------------------
const cpp = [];
cpp.push(`// ${header}`);
cpp.push('#pragma once');
cpp.push('');
cpp.push('#include <array>');
cpp.push('#include <cstddef>');
cpp.push('#include <cstdint>');
cpp.push('#include <string_view>');
cpp.push('');
cpp.push('#include "dwell/core/block_types.h"');
cpp.push('');
cpp.push('namespace dwell::core {');
cpp.push('');
cpp.push(`inline constexpr std::size_t kBlockCount = ${blocks.length};`);
cpp.push(`inline constexpr std::size_t kPropertyCount = ${blocks.reduce((n, b) => n + b.props.length, 0)};`);
cpp.push(`// FNV-1a 64 over the canonical state strings (each followed by '\\n') in runtime id order.`);
cpp.push(`inline constexpr std::uint64_t kRegistryHash = 0x${hashHex}ull;`);
cpp.push('');
cpp.push('// Runtime state ids, by name (non-default property values are appended to the name).');
cpp.push('namespace Materials {');
for (const s of states) cpp.push(`inline constexpr MaterialId ${s.constName} = ${s.id};`);
cpp.push(`inline constexpr MaterialId kCount = ${states.length};`);
cpp.push('}  // namespace Materials');
cpp.push('');
const values = [];
const propDefs = [];
for (const b of blocks) {
  b.propBegin = propDefs.length;
  for (const p of b.props) {
    propDefs.push(`    {"${p.name}", ${values.length}, ${p.values.length}},`);
    for (const v of p.values) values.push(`    "${v}",`);
  }
}
cpp.push('inline constexpr std::array<std::string_view, ' + Math.max(values.length, 1) + '> kPropertyValues{{');
cpp.push(...(values.length ? values : ['    "",']));
cpp.push('}};');
cpp.push('');
cpp.push('inline constexpr std::array<PropertyDef, ' + Math.max(propDefs.length, 1) + '> kProperties{{');
cpp.push(...(propDefs.length ? propDefs : ['    {"", 0, 0},']));
cpp.push('}};');
cpp.push('');
cpp.push('inline constexpr std::array<BlockDef, kBlockCount> kBlocks{{');
for (const b of blocks) {
  cpp.push(`    {"${b.id}", ${b.first}, ${b.count}, ${b.propBegin}, ${b.props.length}},`);
}
cpp.push('}};');
cpp.push('');
cpp.push('inline constexpr std::array<MaterialInfo, Materials::kCount> kMaterials{{');
states.forEach((s, i) => {
  const d = s.block.def;
  const facing = d.facingProperty ? `Facing::k${pascal(s.values[d.facingProperty])}` : 'Facing::kNone';
  const f = [
    `.name = "${s.string}"`,
    `.density_kg_m3 = ${num(d.density)}`,
    `.solid = ${d.shape !== 'empty'}`,
    `.indestructible = ${!!d.indestructible}`,
    `.shape = VoxelShape::${SHAPES[d.shape]}`,
    `.climbable = ${!!d.climbable}`,
    `.facing = ${facing}`,
    `.climb_speed_scale = ${num(d.climbSpeedScale ?? 1)}`,
    `.liquid = ${!!d.liquid}`,
    `.launch_speed = ${num(d.launchSpeed ?? 0)}`,
    `.placeable = ${!!s.placeable}`,
    `.block = ${blocks.indexOf(s.block)}`,
  ];
  cpp.push(`    {${f.join(', ')}},  // ${i}`);
});
cpp.push('}};');
cpp.push('');
cpp.push('}  // namespace dwell::core');
cpp.push('');
writeFileSync(join(root, 'server/core/include/dwell/core/blocks.gen.h'), cpp.join('\n'));

// ---- TypeScript --------------------------------------------------------------------------------
const ts = [];
ts.push(`// ${header}`);
ts.push("import type { TileName } from '../render/textures';");
ts.push('');
ts.push("export type MaterialLook = 'cube' | 'slab' | 'ladder' | 'water';");
ts.push('');
ts.push('/** Texture tiles (render/textures.ts) per face group; untextured materials use `color`. */');
ts.push('export interface MaterialTextures {');
ts.push('  top: TileName;');
ts.push('  side: TileName;');
ts.push('  bottom: TileName;');
ts.push('}');
ts.push('');
ts.push('export interface BlockProperty {');
ts.push('  name: string;');
ts.push('  values: readonly string[];');
ts.push('}');
ts.push('');
ts.push('/** A block: a namespaced id, its typed properties and the run of runtime state ids it owns. */');
ts.push('export interface BlockDef {');
ts.push('  id: string;');
ts.push('  first: number;');
ts.push('  count: number;');
ts.push('  properties: readonly BlockProperty[];');
ts.push('}');
ts.push('');
ts.push('/** One block state with how it is drawn (the physics side lives in the C++ core). */');
ts.push('export interface StateDef {');
ts.push('  /** Runtime state id. */');
ts.push('  id: number;');
ts.push('  /** Canonical string: `ns:name[k=v,…]`, every property, keys alphabetical. */');
ts.push('  state: string;');
ts.push('  block: number;');
ts.push('  values: Readonly<Record<string, string>>;');
ts.push('  look: MaterialLook;');
ts.push('  color: number;');
ts.push('  opacity: number;');
ts.push('  textures?: MaterialTextures;');
ts.push('  /** Ladders: the face whose side the plate faces (0 +X, 1 −X, 4 +Z, 5 −Z). */');
ts.push('  ladderFace?: number;');
ts.push('  /** In the infinite creative palette (§6.5; C++ `Placeable`). */');
ts.push('  placeable: boolean;');
ts.push('}');
ts.push('');
ts.push('/** FNV-1a 64 over the canonical state strings (each followed by "\\n") in id order. */');
ts.push(`export const REGISTRY_HASH = 0x${hashHex}n;`);
ts.push('');
ts.push('export const BLOCK_DEFS: readonly BlockDef[] = [');
for (const b of blocks) {
  const props = b.props.map((p) => `{ name: '${p.name}', values: [${p.values.map((v) => `'${v}'`).join(', ')}] }`);
  ts.push(`  { id: '${b.id}', first: ${b.first}, count: ${b.count}, properties: [${props.join(', ')}] },`);
}
ts.push('];');
ts.push('');
const tex = (t) => {
  if (!t) return null;
  const o = typeof t === 'string' ? { top: t, side: t, bottom: t } : t;
  return `{ top: '${o.top}', side: '${o.side}', bottom: '${o.bottom}' }`;
};
ts.push('export const STATE_DEFS: readonly StateDef[] = [');
for (const s of states) {
  const d = s.block.def;
  const parts = [
    `id: ${s.id}`,
    `state: '${s.string}'`,
    `block: ${blocks.indexOf(s.block)}`,
    `values: { ${s.block.props.map((p) => `${p.name}: '${s.values[p.name]}'`).join(', ')} }`,
    `look: '${s.block.look}'`,
    `color: ${colorNum(d.color)}`,
    `opacity: ${d.opacity ?? 1}`,
  ];
  if (d.textures) parts.push(`textures: ${tex(d.textures)}`);
  if (d.look === 'ladder' && d.facingProperty) {
    parts.push(`ladderFace: ${LADDER_FACE[s.values[d.facingProperty]]}`);
  }
  parts.push(`placeable: ${!!s.placeable}`);
  ts.push(`  { ${parts.join(', ')} },`);
}
ts.push('];');
ts.push('');
writeFileSync(join(root, 'client/src/world/blocks.gen.ts'), ts.join('\n'));

// ---- Shared vector: the canonical strings in id order and the hash (both sides' tests read it) -----
const vec = [`# ${header}`, `hash ${hashHex}`, ...states.map((s) => `${s.id} ${s.string}`), ''];
writeFileSync(join(here, 'vectors.txt'), vec.join('\n'));
console.log(`blocks: ${blocks.length} blocks, ${states.length} states, hash ${hashHex}`);
