#!/usr/bin/env node
// Generates the block registries for C++ and TypeScript from shared/blocks/*.json
// (docs/BLOCK_REGISTRY.md). Outputs are checked in; CI regenerates and fails on any diff.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FACINGS as SHAPE_FACINGS, SLOPE_SHAPES, cubeShape, slabShape, slopeShape } from './shapes.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..');
const header = 'Generated by shared/blocks/gen.mjs from shared/blocks/*.json. Do not edit.';

// ---- Load and expand ---------------------------------------------------------------------------
const files = readdirSync(here)
  .filter((f) => f.endsWith('.json'))
  .sort();
const namespaces = files
  .map((f) => JSON.parse(readFileSync(join(here, f), 'utf8')))
  .sort((a, b) => (a.namespace < b.namespace ? -1 : a.namespace > b.namespace ? 1 : 0));

const NAME = /^[a-z0-9_]+$/;
const SHAPES = { empty: 'kEmpty', full: 'kFull', shaped: 'kShaped' };
const FACINGS = ['north', 'east', 'south', 'west'];
// The face (mesher axis·2 + sign) a ladder's plate sits against, per facing (0 +X, 1 −X, 4 +Z, 5 −Z).
const LADDER_FACE = { east: 0, west: 1, south: 4, north: 5 };
const LOOKS = ['cube', 'shaped', 'ladder', 'water'];

const pascal = (s) => s.replace(/(^|_)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const fail = (m) => {
  throw new Error(`shared/blocks: ${m}`);
};

// Shape families (docs/SLOPE_BLOCKS.md §2): every material listed in `shapeFamilies` gets
// `<m>_slope[facing, flooded, half, shape]` and `<m>_slab[flooded, half]`, linked to the base block
// for look and behaviour. A block entry `{ "name", "family": "slab" | "slope", "of": "<m>" }` places
// that family member at its own slot in the list (with its own `placeable` / `palette`); the rest
// are appended after the explicit blocks, so adding a family keeps earlier ids.
const familyBlock = (base, kind, extra = {}) => {
  if (!base || base.shape !== 'full') fail(`shape family of ${base?.name}: not a full block`);
  const common = {
    density: base.density,
    color: base.color,
    textures: base.textures,
    look: 'shaped',
    shape: 'shaped',
    slopeFamily: kind,
    palette: 'all',
  };
  return kind === 'slope'
    ? {
        ...common,
        name: `${base.name}_slope`,
        properties: {
          facing: SHAPE_FACINGS,
          flooded: ['false', 'true'],
          half: ['bottom', 'top'],
          shape: Object.keys(SLOPE_SHAPES),
        },
        ...extra,
      }
    : {
        ...common,
        name: `${base.name}_slab`,
        properties: { flooded: ['false', 'true'], half: ['bottom', 'top'] },
        ...extra,
      };
};
for (const ns of namespaces) {
  const base = (name) => ns.blocks.find((b) => b.name === name);
  const declared = new Set();
  ns.blocks = ns.blocks.map((def) => {
    if (!def.family) return def;
    declared.add(`${def.of}:${def.family}`);
    const { family, of, name, ...rest } = def;
    return familyBlock(base(of), family, { ...rest, name });
  });
  const generated = [];
  for (const m of ns.shapeFamilies ?? []) {
    for (const kind of ['slope', 'slab']) {
      if (!declared.has(`${m}:${kind}`)) generated.push(familyBlock(base(m), kind));
    }
  }
  ns.blocks = [...ns.blocks, ...generated];
}

const blocks = []; // { id, def, props: [{name, values}], first, count }
const states = []; // { id, block, string, values: {prop: value}, ... }
for (const ns of namespaces) {
  if (!NAME.test(ns.namespace)) fail(`bad namespace ${ns.namespace}`);
  for (const def of ns.blocks) {
    if (!NAME.test(def.name)) fail(`bad block name ${def.name}`);
    const id = `${ns.namespace}:${def.name}`;
    if (blocks.some((b) => b.id === id)) fail(`duplicate block ${id}`);
    const props = Object.keys(def.properties ?? {})
      .sort()
      .map((name) => {
        if (!NAME.test(name)) fail(`${id}: bad property name ${name}`);
        const values = def.properties[name];
        if (!values.length || new Set(values).size !== values.length) fail(`${id}.${name}: values`);
        for (const v of values) if (!NAME.test(v)) fail(`${id}.${name}: bad value ${v}`);
        return { name, values };
      });
    if (!(def.shape in SHAPES)) fail(`${id}: shape ${def.shape}`);
    const look = def.look ?? 'cube';
    if (!LOOKS.includes(look)) fail(`${id}: look ${look}`);
    if (def.facingProperty) {
      const p = props.find((q) => q.name === def.facingProperty);
      if (!p || p.values.some((v) => !FACINGS.includes(v))) fail(`${id}: facingProperty`);
    }
    if (def.shape === 'shaped' && !def.slopeFamily) fail(`${id}: shaped blocks come from shapeFamilies`);
    const count = props.reduce((n, p) => n * p.values.length, 1);
    const block = { id, def, props, first: states.length, count, look };
    blocks.push(block);
    // Mixed radix: the last (alphabetically) property varies fastest.
    for (let i = 0; i < count; ++i) {
      const values = {};
      let rest = i;
      for (let k = props.length - 1; k >= 0; --k) {
        const p = props[k];
        values[p.name] = p.values[rest % p.values.length];
        rest = Math.floor(rest / p.values.length);
      }
      const string = props.length
        ? `${id}[${props.map((p) => `${p.name}=${values[p.name]}`).join(',')}]`
        : id;
      states.push({ id: states.length, block, string, values });
    }
  }
}
if (states[0]?.string !== 'dwell:air') fail('dwell:air must be state 0');
if (states.length > 0xffff) fail('too many states');

// Shapes (shapes.mjs): one baked geometry per distinct (corners, inversion, diagonal); index 0 is
// the empty shape. States of full blocks use the cube, shaped families derive theirs from their
// properties.
const shapeTable = [{ key: 'empty', shape: null }];
const shapeIndexOf = (shape) => {
  const key = JSON.stringify([shape.corners, shape.inverted, shape.diagonal]);
  let i = shapeTable.findIndex((t) => t.key === key);
  if (i < 0) {
    i = shapeTable.length;
    shapeTable.push({ key, shape });
  }
  return i;
};
for (const st of states) {
  const d = st.block.def;
  st.flooded = st.values.flooded === 'true';
  if (d.shape === 'empty') st.shapeIndex = 0;
  else if (d.shape === 'full') st.shapeIndex = shapeIndexOf(cubeShape());
  else st.shapeIndex = shapeIndexOf((d.slopeFamily === 'slope' ? slopeShape : slabShape)(st.values));
}
if (shapeTable.length > 0xffff) fail('too many shapes');

// The slope pieces terrain and the LOD pick for four corner heights (halves of a cell, NW NE SE SW):
// a pattern with a piece of its own keeps it, any other maps to the nearest by total distance, the
// higher on a tie, then the lower index. Pattern index = nw + 3·ne + 9·se + 27·sw. Both languages
// read this table (SLOPE_BLOCKS.md §5), so terrain and LOD agree.
const pieceAllowed = new Set([0, 1 + 3 + 9 + 27, 2 + 6 + 18 + 54]);
for (const shape of Object.keys(SLOPE_SHAPES)) {
  for (const facing of SHAPE_FACINGS) {
    const c = slopeShape({ facing, half: 'bottom', shape }).corners;
    pieceAllowed.add(c[0] + 3 * c[1] + 9 * c[2] + 27 * c[3]);
  }
}
const patternCorners = (p) => [p % 3, Math.floor(p / 3) % 3, Math.floor(p / 9) % 3, Math.floor(p / 27) % 3];
const pieceNearest = Array.from({ length: 81 }, (_, p) => {
  const a = patternCorners(p);
  let best = -1;
  let bestKey = null;
  for (const q of [...pieceAllowed].sort((x, y) => x - y)) {
    const b = patternCorners(q);
    const distance = a.reduce((n, v, i) => n + Math.abs(v - b[i]), 0);
    const height = b.reduce((n, v) => n + v, 0);
    // Smaller distance first, then taller; ties keep the lower index (iterated ascending).
    if (best < 0 || distance < bestKey[0] || (distance === bestKey[0] && height > bestKey[1])) {
      best = q;
      bestKey = [distance, height];
    }
  }
  return best;
});

// Palette (creative inventory) membership: a block's `palette` lists partial property assignments;
// `placeable` alone means the default state.
const defaultOf = (block) => Object.fromEntries(block.props.map((p) => [p.name, p.values[0]]));
for (const block of blocks) {
  const { def } = block;
  if (def.palette === 'all') {
    // Every state is placeable (the shaped families: the client picks the piece, the facing and the
    // half; the server normalises `flooded` from the cell).
    for (const st of states) if (st.block === block) st.placeable = true;
    continue;
  }
  const entries = def.palette ?? (def.placeable ? [{}] : []);
  for (const entry of entries) {
    const want = { ...defaultOf(block), ...entry };
    const s = states.find(
      (st) => st.block === block && block.props.every((p) => st.values[p.name] === want[p.name]),
    );
    if (!s) fail(`${block.id}: palette entry ${JSON.stringify(entry)} matches no state`);
    s.placeable = true;
  }
}

// ---- Registry hash: FNV-1a 64 over each canonical string followed by "\n", in id order ------------
function registryHash() {
  let h = 0xcbf29ce484222325n;
  for (const s of states) {
    for (const byte of Buffer.from(`${s.string}\n`, 'utf8')) {
      h ^= BigInt(byte);
      h = (h * 0x100000001b3n) & 0xffffffffffffffffn;
    }
  }
  return h;
}
const hash = registryHash();
const hashHex = hash.toString(16).padStart(16, '0');

// Constant names: PascalCase block name, plus Property+Value for every non-default value.
const constName = (s) => {
  let n = `k${pascal(s.block.def.name)}`;
  for (const p of s.block.props) {
    if (s.values[p.name] !== p.values[0]) n += pascal(p.name) + pascal(s.values[p.name]);
  }
  return n;
};
const seen = new Set();
for (const s of states) {
  s.constName = constName(s);
  if (seen.has(s.constName)) fail(`constant name clash ${s.constName}`);
  seen.add(s.constName);
}

const colorNum = (c) => `0x${c.replace('#', '').toLowerCase()}`;
const num = (v) => (Number.isInteger(v) ? `${v}.0f` : `${v}f`);

// ---- C++ ---------------------------------------------------------------------------------------
const cpp = [];
cpp.push(`// ${header}`);
cpp.push('#pragma once');
cpp.push('');
cpp.push('#include <array>');
cpp.push('#include <cstddef>');
cpp.push('#include <cstdint>');
cpp.push('#include <string_view>');
cpp.push('');
cpp.push('#include "dwell/core/block_types.h"');
cpp.push('');
cpp.push('namespace dwell::core {');
cpp.push('');
cpp.push(`inline constexpr std::size_t kBlockCount = ${blocks.length};`);
cpp.push(`inline constexpr std::size_t kPropertyCount = ${blocks.reduce((n, b) => n + b.props.length, 0)};`);
cpp.push(`// FNV-1a 64 over the canonical state strings (each followed by '\\n') in runtime id order.`);
cpp.push(`inline constexpr std::uint64_t kRegistryHash = 0x${hashHex}ull;`);
cpp.push('');
cpp.push('// Runtime state ids, by name (non-default property values are appended to the name).');
cpp.push('namespace Materials {');
for (const s of states) cpp.push(`inline constexpr MaterialId ${s.constName} = ${s.id};`);
cpp.push(`inline constexpr MaterialId kCount = ${states.length};`);
cpp.push('}  // namespace Materials');
cpp.push('');
const values = [];
const propDefs = [];
for (const b of blocks) {
  b.propBegin = propDefs.length;
  for (const p of b.props) {
    propDefs.push(`    {"${p.name}", ${values.length}, ${p.values.length}},`);
    for (const v of p.values) values.push(`    "${v}",`);
  }
}
cpp.push('inline constexpr std::array<std::string_view, ' + Math.max(values.length, 1) + '> kPropertyValues{{');
cpp.push(...(values.length ? values : ['    "",']));
cpp.push('}};');
cpp.push('');
cpp.push('inline constexpr std::array<PropertyDef, ' + Math.max(propDefs.length, 1) + '> kProperties{{');
cpp.push(...(propDefs.length ? propDefs : ['    {"", 0, 0},']));
cpp.push('}};');
cpp.push('');
cpp.push('inline constexpr std::array<BlockDef, kBlockCount> kBlocks{{');
for (const b of blocks) {
  cpp.push(`    {"${b.id}", ${b.first}, ${b.count}, ${b.propBegin}, ${b.props.length}},`);
}
cpp.push('}};');
cpp.push('');
const f = (v) => (Number.isInteger(v) ? `${v}.0f` : `${v}f`);
const faceRows = [];
const shapeRows = [];
for (const t of shapeTable) {
  const sh = t.shape;
  const first = faceRows.length;
  for (const face of sh?.faces ?? []) {
    const pts = [...face.pts, ...Array(4 - face.pts.length).fill([0, 0, 0])];
    faceRows.push(`    {${face.tag}, ${face.pts.length}, {${pts.map((p) => `{${p.map(f).join(', ')}}`).join(', ')}}},`);
  }
  shapeRows.push(
    sh
      ? `    {${first}, ${sh.faces.length}, {${sh.corners.join(', ')}}, ${sh.inverted}, ${sh.diagonal}, ${sh.convex}, ${f(sh.volume)}, {{${sh.sides.map((p) => `{${p.join(', ')}}`).join(', ')}}}, ${sh.fullTop}, ${sh.fullBottom}, ${f(sh.minY)}, ${f(sh.maxY)}},`
      : `    {0, 0, {0, 0, 0, 0}, false, 0, true, 0.0f, {{{0, 0}, {0, 0}, {0, 0}, {0, 0}}}, false, false, 0.0f, 0.0f},`,
  );
}
cpp.push(`inline constexpr std::array<ShapeFace, ${Math.max(faceRows.length, 1)}> kShapeFaces{{`);
cpp.push(...faceRows);
cpp.push('}};');
cpp.push('');
cpp.push(`inline constexpr std::array<ShapeInfo, ${shapeRows.length}> kShapes{{`);
cpp.push(...shapeRows);
cpp.push('}};');
cpp.push('');
cpp.push('// Slope piece per corner pattern (nw + 3·ne + 9·se + 27·sw, halves): see shared/blocks/gen.mjs.');
cpp.push(`inline constexpr std::array<std::uint8_t, 81> kPieceNearest{{${pieceNearest.join(', ')}}};`);
cpp.push('');
cpp.push('inline constexpr std::array<MaterialInfo, Materials::kCount> kMaterials{{');
states.forEach((s, i) => {
  const d = s.block.def;
  const facing = d.facingProperty ? `Facing::k${pascal(s.values[d.facingProperty])}` : 'Facing::kNone';
  const f = [
    `.name = "${s.string}"`,
    `.density_kg_m3 = ${num(d.density)}`,
    `.solid = ${d.shape !== 'empty'}`,
    `.indestructible = ${!!d.indestructible}`,
    `.shape = VoxelShape::${SHAPES[d.shape]}`,
    `.shape_index = ${s.shapeIndex}`,
    `.flooded = ${s.flooded}`,
    `.climbable = ${!!d.climbable}`,
    `.facing = ${facing}`,
    `.climb_speed_scale = ${num(d.climbSpeedScale ?? 1)}`,
    `.liquid = ${!!d.liquid}`,
    `.launch_speed = ${num(d.launchSpeed ?? 0)}`,
    `.placeable = ${!!s.placeable}`,
    `.block = ${blocks.indexOf(s.block)}`,
  ];
  cpp.push(`    {${f.join(', ')}},  // ${i}`);
});
cpp.push('}};');
cpp.push('');
cpp.push('}  // namespace dwell::core');
cpp.push('');
writeFileSync(join(root, 'server/core/include/dwell/core/blocks.gen.h'), cpp.join('\n'));

// ---- TypeScript --------------------------------------------------------------------------------
const ts = [];
ts.push(`// ${header}`);
ts.push("import type { TileName } from '../render/textures';");
ts.push('');
ts.push("export type MaterialLook = 'cube' | 'shaped' | 'ladder' | 'water';");
ts.push('');
ts.push('/** Texture tiles (render/textures.ts) per face group; untextured materials use `color`. */');
ts.push('export interface MaterialTextures {');
ts.push('  top: TileName;');
ts.push('  side: TileName;');
ts.push('  bottom: TileName;');
ts.push('}');
ts.push('');
ts.push('export interface BlockProperty {');
ts.push('  name: string;');
ts.push('  values: readonly string[];');
ts.push('}');
ts.push('');
ts.push('/** A block: a namespaced id, its typed properties and the run of runtime state ids it owns. */');
ts.push('export interface BlockDef {');
ts.push('  id: string;');
ts.push('  first: number;');
ts.push('  count: number;');
ts.push('  properties: readonly BlockProperty[];');
ts.push('}');
ts.push('');
ts.push('/** One block state with how it is drawn (the physics side lives in the C++ core). */');
ts.push('export interface StateDef {');
ts.push('  /** Runtime state id. */');
ts.push('  id: number;');
ts.push('  /** Canonical string: `ns:name[k=v,…]`, every property, keys alphabetical. */');
ts.push('  state: string;');
ts.push('  block: number;');
ts.push('  values: Readonly<Record<string, string>>;');
ts.push('  look: MaterialLook;');
ts.push('  color: number;');
ts.push('  opacity: number;');
ts.push('  textures?: MaterialTextures;');
ts.push('  /** Ladders: the face whose side the plate faces (0 +X, 1 −X, 4 +Z, 5 −Z). */');
ts.push('  ladderFace?: number;');
ts.push('  /** Index into SHAPES: the solid\'s geometry in its cell (0 = none). */');
ts.push('  shape: number;');
ts.push('  /** Shaped blocks only: water fills the open part of the cell (SLOPE_BLOCKS.md §3.1). */');
ts.push('  flooded: boolean;');
ts.push('  /** In the infinite creative palette (§6.5; C++ `Placeable`). */');
ts.push('  placeable: boolean;');
ts.push('}');
ts.push('');
ts.push('/** One polygon of a shape: convex, outward-wound, on cell face `tag` (0 +X, 1 −X, 2 +Y, 3 −Y, 4 +Z, 5 −Z) or the sloped surface (6). */');
ts.push('export interface ShapeFace {');
ts.push('  tag: number;');
ts.push('  pts: readonly (readonly [number, number, number])[];');
ts.push('}');
ts.push('');
ts.push('/** Baked solid geometry of a voxel state inside its 1 m cell (shared/blocks/shapes.mjs). */');
ts.push('export interface ShapeDef {');
ts.push('  /** Top-surface corner heights in halves of a cell, NW NE SE SW. */');
ts.push('  corners: readonly [number, number, number, number];');
ts.push('  inverted: boolean;');
ts.push('  /** Top-surface diagonal: 0 NW–SE, 1 NE–SW. */');
ts.push('  diagonal: number;');
ts.push('  convex: boolean;');
ts.push('  volume: number;');
ts.push('  /** Side profile heights (halves) at the face\'s low and high running coordinate, faces +X −X +Z −Z. */');
ts.push('  sides: readonly (readonly [number, number])[];');
ts.push('  fullTop: boolean;');
ts.push('  fullBottom: boolean;');
ts.push('  minY: number;');
ts.push('  maxY: number;');
ts.push('  faces: readonly ShapeFace[];');
ts.push('}');
ts.push('');
ts.push('/** FNV-1a 64 over the canonical state strings (each followed by "\\n") in id order. */');
ts.push(`export const REGISTRY_HASH = 0x${hashHex}n;`);
ts.push('');
ts.push('export const BLOCK_DEFS: readonly BlockDef[] = [');
for (const b of blocks) {
  const props = b.props.map((p) => `{ name: '${p.name}', values: [${p.values.map((v) => `'${v}'`).join(', ')}] }`);
  ts.push(`  { id: '${b.id}', first: ${b.first}, count: ${b.count}, properties: [${props.join(', ')}] },`);
}
ts.push('];');
ts.push('');
ts.push('/** Slope piece per corner pattern (nw + 3·ne + 9·se + 27·sw, halves of a cell): shared/blocks/gen.mjs. */');
ts.push(`export const PIECE_NEAREST: readonly number[] = [${pieceNearest.join(', ')}];`);
ts.push('');
ts.push('export const SHAPES: readonly ShapeDef[] = [');
for (const t of shapeTable) {
  const sh = t.shape;
  if (!sh) {
    ts.push("  { corners: [0, 0, 0, 0], inverted: false, diagonal: 0, convex: true, volume: 0, sides: [[0, 0], [0, 0], [0, 0], [0, 0]], fullTop: false, fullBottom: false, minY: 0, maxY: 0, faces: [] },");
    continue;
  }
  const faces = sh.faces.map((fc) => `{ tag: ${fc.tag}, pts: [${fc.pts.map((p) => `[${p.join(', ')}]`).join(', ')}] }`);
  ts.push(`  { corners: [${sh.corners.join(', ')}], inverted: ${sh.inverted}, diagonal: ${sh.diagonal}, convex: ${sh.convex}, volume: ${sh.volume}, sides: [${sh.sides.map((p) => `[${p.join(', ')}]`).join(', ')}], fullTop: ${sh.fullTop}, fullBottom: ${sh.fullBottom}, minY: ${sh.minY}, maxY: ${sh.maxY}, faces: [${faces.join(', ')}] },`);
}
ts.push('];');
ts.push('');
const tex = (t) => {
  if (!t) return null;
  const o = typeof t === 'string' ? { top: t, side: t, bottom: t } : t;
  return `{ top: '${o.top}', side: '${o.side}', bottom: '${o.bottom}' }`;
};
// Chunked: one literal of a thousand distinct object types is too complex for the type checker.
const CHUNK = 128;
for (let first = 0; first < states.length; first += CHUNK) {
  ts.push(`const STATES_${first / CHUNK}: readonly StateDef[] = [`);
  for (const s of states.slice(first, first + CHUNK)) {
  const d = s.block.def;
  const parts = [
    `id: ${s.id}`,
    `state: '${s.string}'`,
    `block: ${blocks.indexOf(s.block)}`,
    `values: { ${s.block.props.map((p) => `${p.name}: '${s.values[p.name]}'`).join(', ')} }`,
    `look: '${s.block.look}'`,
    `color: ${colorNum(d.color)}`,
    `opacity: ${d.opacity ?? 1}`,
  ];
  if (d.textures) parts.push(`textures: ${tex(d.textures)}`);
  if (d.look === 'ladder' && d.facingProperty) {
    parts.push(`ladderFace: ${LADDER_FACE[s.values[d.facingProperty]]}`);
  }
  parts.push(`shape: ${s.shapeIndex}`);
  parts.push(`flooded: ${s.flooded}`);
  parts.push(`placeable: ${!!s.placeable}`);
  ts.push(`  { ${parts.join(', ')} },`);
  }
  ts.push('];');
  ts.push('');
}
ts.push('export const STATE_DEFS: readonly StateDef[] = [');
for (let first = 0; first < states.length; first += CHUNK) ts.push(`  ...STATES_${first / CHUNK},`);
ts.push('];');
ts.push('');
writeFileSync(join(root, 'client/src/world/blocks.gen.ts'), ts.join('\n'));

// ---- Shared vector: the canonical strings in id order and the hash (both sides' tests read it) -----
const vec = [`# ${header}`, `hash ${hashHex}`, ...states.map((s) => `${s.id} ${s.string}`), ''];
writeFileSync(join(here, 'vectors.txt'), vec.join('\n'));
console.log(`blocks: ${blocks.length} blocks, ${states.length} states, hash ${hashHex}`);
